import { useState, useEffect } from 'react';
import { FileText, Stethoscope, Download, Printer, Copy, Check } from 'lucide-react';
import { useData } from '../data/DataContext';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { formatDate } from '../utils';
import type { HealthProfile, ProfileSummary } from '../types';

export function DoctorBriefPage() {
  const data = useData();
  const [profiles, setProfiles] = useState<HealthProfile[]>([]);
  const [selectedProfileId, setSelectedProfileId] = useState<string>('');
  const [summary, setSummary] = useState<ProfileSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    async function load() {
      try {
        const profs = await data.getProfiles();
        setProfiles(profs);
        if (profs.length > 0) {
          setSelectedProfileId(profs[1].id); // default to Rajesh Mehta for demo
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [data]);

  useEffect(() => {
    async function loadSummary() {
      if (!selectedProfileId) return;
      setGenerating(true);
      try {
        // Simulating AI generation delay
        await new Promise(r => setTimeout(r, 800));
        const s = await data.getProfileSummary(selectedProfileId);
        setSummary(s);
      } catch (err) {
        console.error(err);
      } finally {
        setGenerating(false);
      }
    }
    loadSummary();
  }, [data, selectedProfileId]);

  const handleCopy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="w-8 h-8 border-2 border-sage-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="animate-fade-in max-w-4xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="text-2xl font-heading font-bold text-navy-800 flex items-center gap-2">
            <Stethoscope className="w-6 h-6 text-sage-600" />
            Doctor's Brief
          </h1>
          <p className="text-navy-500 mt-1">Generate a quick 1-page summary for your next consultation.</p>
        </div>
        
        <select 
          className="input-field py-2 pr-10 text-sm font-medium w-auto"
          value={selectedProfileId}
          onChange={(e) => setSelectedProfileId(e.target.value)}
        >
          {profiles.map(p => (
            <option key={p.id} value={p.id}>{p.fullName}'s Brief</option>
          ))}
        </select>
      </div>

      {generating || !summary ? (
        <Card className="flex flex-col items-center justify-center py-16">
          <div className="w-12 h-12 border-4 border-sage-200 border-t-sage-600 rounded-full animate-spin mb-4" />
          <h3 className="text-lg font-heading font-medium text-navy-800">Generating Brief...</h3>
          <p className="text-navy-400 text-sm mt-1">Compiling conditions, meds, and recent vitals.</p>
        </Card>
      ) : (
        <div className="space-y-6">
          <div className="flex justify-end gap-3">
            <Button variant="secondary" size="sm" leftIcon={copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />} onClick={handleCopy}>
              {copied ? 'Copied' : 'Copy Text'}
            </Button>
            <Button variant="secondary" size="sm" leftIcon={<Printer className="w-4 h-4" />}>
              Print
            </Button>
            <Button variant="primary" size="sm" leftIcon={<Download className="w-4 h-4" />}>
              Download PDF
            </Button>
          </div>

          <Card className="bg-white p-8 sm:p-12 shadow-card print:shadow-none print:p-0">
            {/* Brief Header */}
            <div className="border-b border-ivory-200 pb-6 mb-6">
              <div className="flex justify-between items-start">
                <div>
                  <h2 className="text-2xl font-heading font-bold text-navy-800 uppercase tracking-tight">Patient Brief</h2>
                  <p className="text-navy-500 mt-1">Generated by HealthThread on {formatDate(new Date().toISOString())}</p>
                </div>
                <div className="text-right">
                  <h3 className="font-heading font-bold text-xl text-navy-800">{summary.profile.fullName}</h3>
                  <p className="text-navy-500">{summary.profile.gender === 'male' ? 'Male' : 'Female'}, Age {new Date().getFullYear() - new Date(summary.profile.dateOfBirth).getFullYear()}</p>
                  <p className="text-navy-500">Blood Group: {summary.profile.bloodGroup}</p>
                </div>
              </div>
            </div>

            {/* Brief Content */}
            <div className="space-y-8">
              
              {/* Active Conditions */}
              <section>
                <h4 className="font-heading font-semibold text-lg text-sage-700 flex items-center gap-2 mb-3">
                  <FileText className="w-5 h-5" /> Active Conditions
                </h4>
                <ul className="list-disc pl-5 space-y-1 text-navy-700">
                  {summary.profile.id === 'p-2' ? (
                    <>
                      <li><strong>Type 2 Diabetes:</strong> Diagnosed 2015, currently managed.</li>
                      <li><strong>Hypertension:</strong> Diagnosed 2018, active monitoring.</li>
                    </>
                  ) : summary.profile.id === 'p-3' ? (
                    <>
                      <li><strong>Hypothyroidism:</strong> Diagnosed 2012, managed.</li>
                      <li><strong>Vitamin D Deficiency:</strong> Diagnosed 2023, active.</li>
                    </>
                  ) : (
                    <li>No major chronic conditions recorded.</li>
                  )}
                </ul>
              </section>

              {/* Allergies */}
              {summary.profile.id === 'p-2' && (
                <section>
                  <h4 className="font-heading font-semibold text-lg text-red-600 flex items-center gap-2 mb-3">
                    <FileText className="w-5 h-5" /> Allergies
                  </h4>
                  <div className="flex gap-2">
                    <Badge variant="gray" className="text-red-700 bg-red-50 border border-red-200">Penicillin (Moderate)</Badge>
                    <Badge variant="gray" className="text-orange-700 bg-orange-50 border border-orange-200">Sulfa Drugs (Mild)</Badge>
                  </div>
                </section>
              )}
              {summary.profile.id === 'p-3' && (
                <section>
                  <h4 className="font-heading font-semibold text-lg text-red-600 flex items-center gap-2 mb-3">
                    <FileText className="w-5 h-5" /> Allergies
                  </h4>
                  <div className="flex gap-2">
                    <Badge variant="gray" className="text-red-700 bg-red-50 border border-red-200">Aspirin (Severe)</Badge>
                  </div>
                </section>
              )}

              {/* Current Medications */}
              <section>
                <h4 className="font-heading font-semibold text-lg text-ocean-600 flex items-center gap-2 mb-3">
                  <FileText className="w-5 h-5" /> Current Medications
                </h4>
                <div className="bg-ivory-50 rounded-xl p-4 border border-ivory-200">
                  {summary.profile.id === 'p-2' ? (
                    <ul className="space-y-3 text-sm text-navy-700">
                      <li className="grid grid-cols-3 gap-2">
                        <span className="font-medium">Metformin 500mg</span>
                        <span>Twice daily</span>
                        <span className="text-navy-500">Dr. Sharma</span>
                      </li>
                      <li className="grid grid-cols-3 gap-2">
                        <span className="font-medium">Amlodipine 5mg</span>
                        <span>Once daily (Morning)</span>
                        <span className="text-navy-500">Dr. Patel</span>
                      </li>
                      <li className="grid grid-cols-3 gap-2">
                        <span className="font-medium">Atorvastatin 10mg</span>
                        <span>Once daily (Night)</span>
                        <span className="text-navy-500">Dr. Patel</span>
                      </li>
                    </ul>
                  ) : summary.profile.id === 'p-3' ? (
                    <ul className="space-y-3 text-sm text-navy-700">
                      <li className="grid grid-cols-3 gap-2">
                        <span className="font-medium">Levothyroxine 50mcg</span>
                        <span>Once daily (Morning)</span>
                        <span className="text-navy-500">Dr. Gupta</span>
                      </li>
                      <li className="grid grid-cols-3 gap-2">
                        <span className="font-medium">Vitamin D3 60000IU</span>
                        <span>Once weekly</span>
                        <span className="text-navy-500">Self</span>
                      </li>
                    </ul>
                  ) : (
                    <p className="text-sm text-navy-500">No active medications.</p>
                  )}
                </div>
              </section>

              {/* Recent Vitals & Reports */}
              <section className="grid sm:grid-cols-2 gap-6">
                <div>
                  <h4 className="font-heading font-semibold text-lg text-peach-600 flex items-center gap-2 mb-3">
                    <FileText className="w-5 h-5" /> Latest Vitals
                  </h4>
                  {summary.latestVital ? (
                    <div className="p-4 rounded-xl border border-ivory-200 bg-white">
                      <p className="text-sm text-navy-500 mb-1">{formatDate(summary.latestVital.date)}</p>
                      <p className="font-medium text-navy-800 capitalize">{summary.latestVital.type}</p>
                      <p className="text-xl font-heading font-bold text-sage-600 mt-1">{summary.latestVital.value}</p>
                    </div>
                  ) : (
                    <p className="text-sm text-navy-500">No recent vitals.</p>
                  )}
                </div>
                <div>
                  <h4 className="font-heading font-semibold text-lg text-lavender-600 flex items-center gap-2 mb-3">
                    <FileText className="w-5 h-5" /> Latest Report
                  </h4>
                  {summary.latestReport ? (
                    <div className="p-4 rounded-xl border border-ivory-200 bg-white">
                      <p className="text-sm text-navy-500 mb-1">{formatDate(summary.latestReport.date)}</p>
                      <p className="font-medium text-navy-800">{summary.latestReport.title}</p>
                    </div>
                  ) : (
                    <p className="text-sm text-navy-500">No recent reports.</p>
                  )}
                </div>
              </section>

            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
